# Generated by Django 5.0.11 on 2025-02-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/default-user-image.png', null=True, upload_to=''),
        ),
    ]
