# Generated by Django 5.0.11 on 2025-01-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksData',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(blank=True, db_collation='Hebrew_CI_AS', max_length=150, null=True)),
                ('author', models.CharField(blank=True, db_collation='Hebrew_CI_AS', max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, db_collation='Hebrew_CI_AS', max_length=100, null=True)),
                ('images', models.URLField(blank=True, max_length=500, null=True)),
                ('book_description', models.TextField(blank=True, db_collation='Hebrew_CI_AS', null=True)),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('book_rating', models.FloatField(blank=True, null=True)),
                ('book_pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books_data',
            },
        ),
    ]
