# Generated by Django 5.0.11 on 2025-03-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
