# Generated by Django 5.0.11 on 2025-01-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_booksdata_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksdata',
            name='book_title',
            field=models.CharField(blank=True, db_collation='Hebrew_CI_AS', max_length=150, null=True),
        ),
    ]
