# Generated by Django 5.0.11 on 2025-03-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_bookslist_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='data',
            new_name='date',
        ),
    ]
