# Generated by Django 5.0.11 on 2025-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_booksdata_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdata',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
