# Generated by Django 5.0.11 on 2025-01-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_booksdata_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdata',
            name='book_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
