# Generated by Django 5.0.11 on 2025-03-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_reviews_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='date',
            new_name='data',
        ),
    ]
