# Generated by Django 5.0.11 on 2025-02-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_booksdata_book_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booksdata',
            table=None,
        ),
    ]
