# Generated by Django 5.0.11 on 2025-03-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_date_reviews_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='data',
            new_name='date',
        ),
    ]
