# Generated by Django 5.0.11 on 2025-02-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_booksdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booksdata',
            table='books_data',
        ),
    ]
