# Generated by Django 5.0.11 on 2025-02-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksdata',
            name='book_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
