# Generated by Django 5.0.11 on 2025-02-15 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_alter_booksdata_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksdata',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
