# Generated by Django 5.0.11 on 2025-02-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_booksdata_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
