# Generated by Django 5.0.11 on 2025-02-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_categorie_booksdata_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksdata',
            name='category',
        ),
        migrations.AddField(
            model_name='booksdata',
            name='categorie',
            field=models.CharField(blank=True, db_collation='Hebrew_CI_AS', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
