# Generated by Django 5.0.11 on 2025-02-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_category_remove_booksdata_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
